# # 7/26/2020
# In this exercise, we will revisit the TED Talks from the first chapter. You have been a given a dataframe ted consisting of 5 TED Talks. Your task is to clean these talks using techniques discussed earlier by writing a function preprocess and applying it to the transcript feature of the dataframe.

# The stopwords list is available as stopwords.

# Function to preprocess text
def preprocess(text):
  	# Create Doc object
    doc = nlp(text, disable=['ner', 'parser'])
    # Generate lemmas
    lemmas = [token.lemma_ for token in doc]
    # Remove stopwords and non-alphabetic characters
    a_lemmas = [lemma for lemma in lemmas 
            if lemma.isalpha() and lemma not in stopwords]
    
    return ' '.join(a_lemmas)
  
# Apply preprocess to ted['transcript']
ted['transcript'] = ted['transcript'].apply(preprocess)
print(ted['transcript'])

# <script.py> output:
#     0     talk new lecture ted illusion create ted try r...
#     1     representation brain brain break left half log...
#     2     great honor today share digital universe creat...
#     3     passion music technology thing combination thi...
#     4     use want computer new program programming requ...
#     5     neuroscientist mixed background physics medici...
#     6     pat mitchell day january begin like work love ...
#     7     taylor wilson year old nuclear physicist littl...
#     8     grow northern ireland right north end absolute...
#     9     publish article new york times modern love col...
#     10    joseph member parliament kenya picture maasai ...
#     11    hi talk little bit music machine life specific...
#     12    hi let ask audience question lie child raise h...
#     13    historical record allow know ancient greeks dr...
#     14    good morning little boy experience change life...
#     15    slide year ago time short slide morning time w...
#     16    like world like share year old love story poor...
#     17    fail woman fail feminist passionate opinion ge...
#     18    revolution century significant longevity revol...
#     19    today baffle lady observe shell soul dwellsand...
#     Name: transcript, dtype: object


