# # 7/11/2020
# Once the vectorizer has been fit to the data, it can be used to transform the text to an array representing the word counts. This array will have a row per block of text and a column for each of the features generated by the vectorizer that you observed in the last exercise.

# The vectorizer to you fit in the last exercise (cv) is available in your workspace.

# Apply the vectorizer
cv_transformed = cv.transform(speech_df['text_clean'])

# Print the full array
cv_array = cv_transformed.toarray()

# Print the shape of cv_array
print(cv_array.shape)

# <script.py> output:
#     [[0 0 0 ... 0 0 0]
#      [0 0 0 ... 0 0 0]
#      [0 1 0 ... 0 0 0]
#      ...
#      [0 1 0 ... 0 0 0]
#      [0 0 0 ... 0 0 0]
#      [0 0 0 ... 0 0 0]]

# <script.py> output:
#     (58, 9043)
